services:
  notes_api:
    build: .
    container_name: notes_api_app
    ports:
      - "8000:8000"
    environment:
      APP_ENV: "dev"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
